### ISSUE TITLE
How to update Toml file if I add new position without recreate file?

### ISSUE THREAD

**Issue by syorito-hatsuki** [Peanuuutz/tomlkt#1]
I wanted to ask that on Discord, but u don't have it(

**Comment by Peanuuutz** [comment]
Hmm...what is `add new position`?

> My discord: Peanutz_OwO#2750

**Comment by syorito-hatsuki** [comment]
> Hmm...what is `add new position`?
> 
> > My discord: Peanutz_OwO#2750

So as example I have in version 1.0 of my app something like this
```toml
[server]
ip = "..."
port = 8080

[remote-storage]
user = "..."
password = "..."
```

and in version 1.1 I changed it to
```toml
[server]
ip = "..."
port = 8080
ssl = false

[remote-storage]
user = "..."
password = "..."
```

How todo correctly for get new param to toml file with out lost already edited values in file.
