### ISSUE TITLE
New crash with 0.3.3 `UnexpectedTokenException`

### ISSUE THREAD

**Issue by Wavesonics** [Peanuuutz/tomlkt#51]
I have a test that just started throwing:
`internal.UnexpectedTokenException: '\r' (L1)`

On this data:
```toml
[[events]]
id = 1
order = 0
date = "Date 1"
content = """
Content 1"""

[[events]]
id = 2
order = 1
date = "Date 2"
content = """
Content 2"""

[[events]]
id = 3
order = 2
date = "Date 3"
content = """
Content 3"""
```
