### ISSUE TITLE
ArrayIndexOutOfBoundsException trying to deserialize file that was created by serializing the same object

### ISSUE THREAD

**Issue by Vodes** [Peanuuutz/tomlkt#72]
```
> Task :app:run FAILED
2024-11-30 19:34:05 - [W] - Config File has been created at: C:\Users\Alex\AppData\Roaming\Styx-Server\config.toml
Please do the necessary edits.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at net.peanuuutz.tomlkt.TomlElementKt.getByPathRecursively(TomlElement.kt:1486)
        at net.peanuuutz.tomlkt.TomlElementKt.get(TomlElement.kt:1175)
        at net.peanuuutz.tomlkt.Toml.decodeFromString(Toml.kt:178)
        at moe.styx.common.config.UnifiedConfig$Companion.getCurrent(UnifiedConfig.kt:287)
        at org.example.AppKt.main(App.kt:12)
        at org.example.AppKt.main(App.kt)
```

<details>
<summary>Generated File</summary>

```toml

[General]
# Enable or disable debug logging. Will prefer 'DEBUG' env variable if any.
debug = false
# Base URL for styx-web. Will prefer 'BASE_URL' env variable if any.
siteBaseURL = "https://example.com"
# Base URL for styx-api. Will prefer 'API_BASE_URL' env variable if any.
apiBaseURL = "https://api.example.com"
# Base URL for the images directory. Will prefer 'IMAGE_URL' env variable if any.
# You can leave this empty and use the API for image access under 'apiBaseURL/image/file.ext' but it will be slower than a good webserver. 
imageBaseURL = "https://images.example.com"
# Directory containing all the images. Will prefer 'IMAGE_DIR' env variable if any.
imageDir = "/images"
# Directory containing all the desktop app builds. Will prefer 'BUILD_DIR' env variable if any.
buildDir = "/builds"
# Directory containing all the android app builds. Will prefer 'ANDROID_BUILD_DIR' env variable if any.
androidBuildDir = "/android-builds"
# Directory containing all the mpv bundles. Will prefer 'MPV_DIR' env variable if any.
mpvDir = "/mpv"
# User-Agent used for all outgoing http requests. Will prefer 'USER_AGENT' env variable if any.
httpUserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
# themoviedb.org API Token. Will prefer 'TMDB_TOKEN' env variable if any.
tmdbToken = ""

[Database-Config]
# Host or IP of the database. Will prefer 'DB_HOST' env variable if any.
host = ""
# Username for the database.  Will prefer 'DB_USER' env variable if any.
user = ""
# Password for the database.  Will prefer 'DB_PASS' env variable if any.
pass = ""

[StyxWeb-Config]
# Host to bind for styx-web.
# Leaving this empty assumes 0.0.0.0 when running in a docker and localhost otherwise.
serveHost = ""
# Port to bind for styx-web.
servePort = 8080
# Discord Auth Token to be used, essentially skipping login. DO NOT USE ON PUBLICLY HOSTED INSTANCES.
debugAuthToken = ""

[StyxAPI-Config]
# Host to bind for styx-api.
# Leaving this empty assumes 0.0.0.0 when running in a docker and localhost otherwise.
serveHost = ""
# Port to bind for styx-api.
servePort = 8081
# Enable or disable checking the APPSECRET that clients use as verification that a build is legitimate.
# Secrets are to be put in a 'SECRETS' file in the same directory as this config.
# Just plain text and each line is a separate secret.
enableSecretsCheck = true
# Nginx Access Log file used for traffic logging. Leaving this empty just disables the functionality.
# Recommended to create a separate one and filter it to /watch routes to not parse too much useless data.
nginxLogFile = ""

[Discord-Config]
# Discord Bot Token used for the downloader to notify about new episodes.
# Will prefer 'DISCORD_TOKEN' env variable if any.
botToken = ""
# Channel where some backend logs like new devices being added etc. are posted to.
# In the format: https://discord.com/channels/<ServerID>/<ChannelID>
# Will prefer 'LOG_CHANNEL_URL' env variable if any.
logChannelURL = ""
# The channel announcements for new episodes will be posted in.
# In the format: https://discord.com/channels/<ServerID>/<ChannelID>
# Will prefer 'DISCORD_CHANNEL_URL' env variable if any.
announcementChannelURL = ""
# The role ID that users should have if they should be pinged in the channel for new episodes of favourites.
# Will prefer 'DISCORD_PING_ROLE' env variable if any.
announcementPingRole = ""
# The role ID that users should have if they should be directly messaged by the bot for new episodes of favourites.
# Will prefer 'DISCORD_DM_ROLE' env variable if any.
announcementDmRole = ""
# Used by styx-web for manual imports. Should ideally be in the same channel as the one above.
# Will prefer 'DISCORD_WEBHOOK' env variable if any.
announcementWebhookURL = ""
# Used by styx-dl to show the current schedule in a message.
# If this is a channel URL it will post a new message in that channel and update the config accordingly.
# Will prefer 'DISCORD_SCHEDULE_MSG' env variable if any.
scheduleMessageURL = ""
# Client ID used for authentication. Will prefer 'DISCORD_CLIENT_ID' env variable if any.
discordClientID = ""
# Client Secret used for authentication. Will prefer 'DISCORD_CLIENT_SECRET' env variable if any.
discordClientSecret = ""

[Downloader-Config]
# Ignore episodes like 'One Piece - Egghead SP1' or 'One Piece E1078.5'
ignoreSpecialsAndPoint5 = true
# FTP Connection used if there isn't any explicitly passed in the downloader option.
defaultFTPConnectionString = ""

[Downloader-Config.RSS-Config]
# Directory where only temporary downloads will go to.
tempDir = ""
# Directory where downloads will be kept for seeding.
seedDir = ""

# Templates you can use in torrent/usenet options as shortcuts for feeds to check.
# Do not include a query string in templates if you want to use dynamic queries in the webui!
# '%tosho%my hero academia' would result in 'https://feed.animetosho.org/rss2?q=my+hero+academia'

[Downloader-Config.RSS-Config.feedTemplates]
tosho = "https://feed.animetosho.org/rss2"

[Downloader-Config.Torrent-Client]
# Type of torrent client, can be Flood or Transmission.
clientType = "Transmission"
# URL to the client.
clientURL = ""
# Username used for the client.
clientUser = ""
# Password used for the client.
clientPass = ""

[Downloader-Config.SABnzbd-Client]
# URL to the SABnzbd instance.
sabURL = ""
# API-Key for the instance.
sabApiKey = ""

[Downloader-Config.IRC-Config]
# Whitelisted XDCC Bots to listen for.
whitelistedXDCCBots = [
    "StyxXDCC",
    "CR-ARUTHA|NEW"
]

# A map of server host and the channels to be listened to.

[Downloader-Config.IRC-Config.servers]
"irc.rizon.net" = [
    "#subsplease",
    "#Styx-XDCC"
]
```

</details>

Also passes the [official linter](https://www.toml-lint.com/) for what it's worth.

Sample to test with is here: https://github.com/Vodes/Tomlkt-Sample/

The object I'm using is here: https://github.com/Vodes/Styx-Common/blob/0.4.1/styx-common/src/jvmMain/kotlin/moe/styx/common/config/UnifiedConfig.kt

**Comment by Peanuuutz** [comment]
Hmm... I cannot reproduce the problem.
<details>

<summary>Data models</summary>

```kotlin
@Serializable
data class UnifiedConfig(
    @SerialName("General")
    val base: BaseConfig = BaseConfig(),
    @SerialName("Database-Config")
    val dbConfig: DatabaseConfig = DatabaseConfig(),
    @SerialName("StyxWeb-Config")
    val webConfig: WebConfig = WebConfig(),
    @SerialName("StyxAPI-Config")
    val apiConfig: APIConfig = APIConfig(),
    @SerialName("Discord-Config")
    val discord: DiscordConfig = DiscordConfig(),
    @SerialName("Downloader-Config")
    val dlConfig: DownloaderConfig = DownloaderConfig()
)

@Serializable
data class BaseConfig(
    @TomlComment("Enable or disable debug logging. Will prefer 'DEBUG' env variable if any.")
    private val debug: Boolean = false,

    @TomlComment("Base URL for styx-web. Will prefer 'BASE_URL' env variable if any.")
    private val siteBaseURL: String = "https://example.com",

    @TomlComment("Base URL for styx-api. Will prefer 'API_BASE_URL' env variable if any.")
    private val apiBaseURL: String = "https://api.example.com",

    @TomlComment(
        """
        Base URL for the images directory. Will prefer 'IMAGE_URL' env variable if any.
        You can leave this empty and use the API for image access under 'apiBaseURL/image/file.ext' but it will be slower than a good webserver. 
    """
    )
    private val imageBaseURL: String = "https://images.example.com",

    @TomlComment("Directory containing all the images. Will prefer 'IMAGE_DIR' env variable if any.")
    private val imageDir: String = "/images",

    @TomlComment("Directory containing all the desktop app builds. Will prefer 'BUILD_DIR' env variable if any.")
    private val buildDir: String = "/builds",

    @TomlComment("Directory containing all the android app builds. Will prefer 'ANDROID_BUILD_DIR' env variable if any.")
    private val androidBuildDir: String = "/android-builds",

    @TomlComment("Directory containing all the mpv bundles. Will prefer 'MPV_DIR' env variable if any.")
    private val mpvDir: String = "/mpv",

    @TomlComment("User-Agent used for all outgoing http requests. Will prefer 'USER_AGENT' env variable if any.")
    private val httpUserAgent: String = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",

    @TomlComment("themoviedb.org API Token. Will prefer 'TMDB_TOKEN' env variable if any.")
    private val tmdbToken: String = ""
)

@Serializable
data class DatabaseConfig(
    @TomlComment("Host or IP of the database. Will prefer 'DB_HOST' env variable if any.")
    private val host: String = "",

    @TomlComment("Username for the database.  Will prefer 'DB_USER' env variable if any.")
    private val user: String = "",

    @TomlComment("Password for the database.  Will prefer 'DB_PASS' env variable if any.")
    private val pass: String = ""
)

@Serializable
data class WebConfig(
    @TomlComment(
        """
        Host to bind for styx-web.
        Leaving this empty assumes 0.0.0.0 when running in a docker and localhost otherwise.
    """
    )
    private val serveHost: String = "",
    @TomlComment("Port to bind for styx-web.")
    val servePort: Int = 8080,
    @TomlComment("Discord Auth Token to be used, essentially skipping login. DO NOT USE ON PUBLICLY HOSTED INSTANCES.")
    val debugAuthToken: String = ""
)

@Serializable
data class APIConfig(
    @TomlComment(
        """
        Host to bind for styx-api.
        Leaving this empty assumes 0.0.0.0 when running in a docker and localhost otherwise.
    """
    )
    private val serveHost: String = "",
    @TomlComment("Port to bind for styx-api.")
    val servePort: Int = 8081,
    @TomlComment(
        """
        Enable or disable checking the APPSECRET that clients use as verification that a build is legitimate.
        Secrets are to be put in a 'SECRETS' file in the same directory as this config.
        Just plain text and each line is a separate secret.
    """
    )
    val enableSecretsCheck: Boolean = true,
    @TomlComment(
        """
        Nginx Access Log file used for traffic logging. Leaving this empty just disables the functionality.
        Recommended to create a separate one and filter it to /watch routes to not parse too much useless data.
    """
    )
    val nginxLogFile: String = "",
)

@Serializable
data class DiscordConfig(
    @TomlComment(
        """
        Discord Bot Token used for the downloader to notify about new episodes.
        Will prefer 'DISCORD_TOKEN' env variable if any.
    """
    )
    private val botToken: String = "",

    @TomlComment(
        """
        Channel where some backend logs like new devices being added etc. are posted to.
        In the format: https://discord.com/channels/<ServerID>/<ChannelID>
        Will prefer 'LOG_CHANNEL_URL' env variable if any.
    """
    )
    private val logChannelURL: String = "",

    @TomlComment(
        """
        The channel announcements for new episodes will be posted in.
        In the format: https://discord.com/channels/<ServerID>/<ChannelID>
        Will prefer 'DISCORD_CHANNEL_URL' env variable if any.
    """
    )
    private val announcementChannelURL: String = "",

    @TomlComment(
        """
        The role ID that users should have if they should be pinged in the channel for new episodes of favourites.
        Will prefer 'DISCORD_PING_ROLE' env variable if any.
    """
    )
    private val announcementPingRole: String = "",

    @TomlComment(
        """
        The role ID that users should have if they should be directly messaged by the bot for new episodes of favourites.
        Will prefer 'DISCORD_DM_ROLE' env variable if any.
    """
    )
    private val announcementDmRole: String = "",

    @TomlComment(
        """
        Used by styx-web for manual imports. Should ideally be in the same channel as the one above.
        Will prefer 'DISCORD_WEBHOOK' env variable if any.
        """
    )
    private val announcementWebhookURL: String = "",

    @TomlComment(
        """
        Used by styx-dl to show the current schedule in a message.
        If this is a channel URL it will post a new message in that channel and update the config accordingly.
        Will prefer 'DISCORD_SCHEDULE_MSG' env variable if any.
        """
    )
    private val scheduleMessageURL: String = "",
    @TomlComment("Client ID used for authentication. Will prefer 'DISCORD_CLIENT_ID' env variable if any.")
    private val discordClientID: String = "",
    @TomlComment("Client Secret used for authentication. Will prefer 'DISCORD_CLIENT_SECRET' env variable if any.")
    private val discordClientSecret: String = ""
)

@Serializable
data class DownloaderConfig(
    @TomlComment("Ignore episodes like 'One Piece - Egghead SP1' or 'One Piece E1078.5'")
    val ignoreSpecialsAndPoint5: Boolean = true,
    @TomlComment("FTP Connection used if there isn't any explicitly passed in the downloader option.")
    val defaultFTPConnectionString: String = "",
    @SerialName("RSS-Config")
    val rssConfig: RSSConfig = RSSConfig(),
    @SerialName("Torrent-Client")
    val torrentConfig: TorrentConfig = TorrentConfig(),
    @SerialName("SABnzbd-Client")
    val sabnzbdConfig: SABnzbdConfig = SABnzbdConfig(),
    @SerialName("IRC-Config")
    val ircConfig: IRCConfig = IRCConfig()
)

@Serializable
data class RSSConfig(
    @TomlComment("Directory where only temporary downloads will go to.")
    val tempDir: String = "",
    @TomlComment("Directory where downloads will be kept for seeding.")
    val seedDir: String = "",
    @TomlComment(
        """
            Templates you can use in torrent/usenet options as shortcuts for feeds to check.
            Do not include a query string in templates if you want to use dynamic queries in the webui!
            '%tosho%my hero academia' would result in 'https://feed.animetosho.org/rss2?q=my+hero+academia'
        """
    )
    val feedTemplates: Map<String, String> = mapOf("tosho" to "https://feed.animetosho.org/rss2"),
)

@Serializable
data class TorrentConfig(
    @TomlComment("Type of torrent client, can be Flood or Transmission.")
    val clientType: String = "Transmission",
    @TomlComment("URL to the client.")
    val clientURL: String = "",
    @TomlComment("Username used for the client.")
    val clientUser: String = "",
    @TomlComment("Password used for the client.")
    val clientPass: String = ""
)

@Serializable
data class SABnzbdConfig(
    @TomlComment("URL to the SABnzbd instance.")
    val sabURL: String = "",
    @TomlComment("API-Key for the instance.")
    val sabApiKey: String = ""
)

@Serializable
data class IRCConfig(
    @TomlComment("A map of server host and the channels to be listened to.")
    val servers: Map<String, List<String>> = mapOf("irc.rizon.net" to listOf("#subsplease", "#Styx-XDCC")),
    @TomlComment("Whitelisted XDCC Bots to listen for.")
    val whitelistedXDCCBots: List<String> = listOf("StyxXDCC", "CR-ARUTHA|NEW")
)
```

</details>

<details>

<summary>Your generated file</summary>

```toml
[General]
# Enable or disable debug logging. Will prefer 'DEBUG' env variable if any.
debug = false
# Base URL for styx-web. Will prefer 'BASE_URL' env variable if any.
siteBaseURL = "https://example.com"
# Base URL for styx-api. Will prefer 'API_BASE_URL' env variable if any.
apiBaseURL = "https://api.example.com"
# Base URL for the images directory. Will prefer 'IMAGE_URL' env variable if any.
# You can leave this empty and use the API for image access under 'apiBaseURL/image/file.ext' but it will be slower than a good webserver. 
imageBaseURL = "https://images.example.com"
# Directory containing all the images. Will prefer 'IMAGE_DIR' env variable if any.
imageDir = "/images"
# Directory containing all the desktop app builds. Will prefer 'BUILD_DIR' env variable if any.
buildDir = "/builds"
# Directory containing all the android app builds. Will prefer 'ANDROID_BUILD_DIR' env variable if any.
androidBuildDir = "/android-builds"
# Directory containing all the mpv bundles. Will prefer 'MPV_DIR' env variable if any.
mpvDir = "/mpv"
# User-Agent used for all outgoing http requests. Will prefer 'USER_AGENT' env variable if any.
httpUserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
# themoviedb.org API Token. Will prefer 'TMDB_TOKEN' env variable if any.
tmdbToken = ""

[Database-Config]
# Host or IP of the database. Will prefer 'DB_HOST' env variable if any.
host = ""
# Username for the database.  Will prefer 'DB_USER' env variable if any.
user = ""
# Password for the database.  Will prefer 'DB_PASS' env variable if any.
pass = ""

[StyxWeb-Config]
# Host to bind for styx-web.
# Leaving this empty assumes 0.0.0.0 when running in a docker and localhost otherwise.
serveHost = ""
# Port to bind for styx-web.
servePort = 8080
# Discord Auth Token to be used, essentially skipping login. DO NOT USE ON PUBLICLY HOSTED INSTANCES.
debugAuthToken = ""

[StyxAPI-Config]
# Host to bind for styx-api.
# Leaving this empty assumes 0.0.0.0 when running in a docker and localhost otherwise.
serveHost = ""
# Port to bind for styx-api.
servePort = 8081
# Enable or disable checking the APPSECRET that clients use as verification that a build is legitimate.
# Secrets are to be put in a 'SECRETS' file in the same directory as this config.
# Just plain text and each line is a separate secret.
enableSecretsCheck = true
# Nginx Access Log file used for traffic logging. Leaving this empty just disables the functionality.
# Recommended to create a separate one and filter it to /watch routes to not parse too much useless data.
nginxLogFile = ""

[Discord-Config]
# Discord Bot Token used for the downloader to notify about new episodes.
# Will prefer 'DISCORD_TOKEN' env variable if any.
botToken = ""
# Channel where some backend logs like new devices being added etc. are posted to.
# In the format: https://discord.com/channels/<ServerID>/<ChannelID>
# Will prefer 'LOG_CHANNEL_URL' env variable if any.
logChannelURL = ""
# The channel announcements for new episodes will be posted in.
# In the format: https://discord.com/channels/<ServerID>/<ChannelID>
# Will prefer 'DISCORD_CHANNEL_URL' env variable if any.
announcementChannelURL = ""
# The role ID that users should have if they should be pinged in the channel for new episodes of favourites.
# Will prefer 'DISCORD_PING_ROLE' env variable if any.
announcementPingRole = ""
# The role ID that users should have if they should be directly messaged by the bot for new episodes of favourites.
# Will prefer 'DISCORD_DM_ROLE' env variable if any.
announcementDmRole = ""
# Used by styx-web for manual imports. Should ideally be in the same channel as the one above.
# Will prefer 'DISCORD_WEBHOOK' env variable if any.
announcementWebhookURL = ""
# Used by styx-dl to show the current schedule in a message.
# If this is a channel URL it will post a new message in that channel and update the config accordingly.
# Will prefer 'DISCORD_SCHEDULE_MSG' env variable if any.
scheduleMessageURL = ""
# Client ID used for authentication. Will prefer 'DISCORD_CLIENT_ID' env variable if any.
discordClientID = ""
# Client Secret used for authentication. Will prefer 'DISCORD_CLIENT_SECRET' env variable if any.
discordClientSecret = ""

[Downloader-Config]
# Ignore episodes like 'One Piece - Egghead SP1' or 'One Piece E1078.5'
ignoreSpecialsAndPoint5 = true
# FTP Connection used if there isn't any explicitly passed in the downloader option.
defaultFTPConnectionString = ""

[Downloader-Config.RSS-Config]
# Directory where only temporary downloads will go to.
tempDir = ""
# Directory where downloads will be kept for seeding.
seedDir = ""

# Templates you can use in torrent/usenet options as shortcuts for feeds to check.
# Do not include a query string in templates if you want to use dynamic queries in the webui!
# '%tosho%my hero academia' would result in 'https://feed.animetosho.org/rss2?q=my+hero+academia'

[Downloader-Config.RSS-Config.feedTemplates]
tosho = "https://feed.animetosho.org/rss2"

[Downloader-Config.Torrent-Client]
# Type of torrent client, can be Flood or Transmission.
clientType = "Transmission"
# URL to the client.
clientURL = ""
# Username used for the client.
clientUser = ""
# Password used for the client.
clientPass = ""

[Downloader-Config.SABnzbd-Client]
# URL to the SABnzbd instance.
sabURL = ""
# API-Key for the instance.
sabApiKey = ""

[Downloader-Config.IRC-Config]
# Whitelisted XDCC Bots to listen for.
whitelistedXDCCBots = [
    "StyxXDCC",
    "CR-ARUTHA|NEW"
]

# A map of server host and the channels to be listened to.

[Downloader-Config.IRC-Config.servers]
"irc.rizon.net" = [
    "#subsplease",
    "#Styx-XDCC"
]
```

</details>

<details>

<summary>With the following test code, it works without problem</summary>

```kotlin
val config = Toml.decodeFromString(UnifiedConfig.serializer(), Generated)
println(config)
/*
UnifiedConfig(
    base=BaseConfig(
        debug=false, 
        siteBaseURL=https://example.com, 
        apiBaseURL=https://api.example.com, 
        imageBaseURL=https://images.example.com, 
        imageDir=/images, 
        buildDir=/builds, 
        androidBuildDir=/android-builds, 
        mpvDir=/mpv, 
        httpUserAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36, 
        tmdbToken=
    ), 
    dbConfig=DatabaseConfig(
        host=, 
        user=, 
        pass=
    ), 
    webConfig=WebConfig(
        serveHost=, 
        servePort=8080, 
        debugAuthToken=
    ), 
    apiConfig=APIConfig(
        serveHost=, 
        servePort=8081, 
        enableSecretsCheck=true, 
        nginxLogFile=
    ), 
    discord=DiscordConfig(
        botToken=, 
        logChannelURL=, 
        announcementChannelURL=, 
        announcementPingRole=, 
        announcementDmRole=, 
        announcementWebhookURL=, 
        scheduleMessageURL=, 
        discordClientID=, 
        discordClientSecret=
    ), 
    dlConfig=DownloaderConfig(
        ignoreSpecialsAndPoint5=true, 
        defaultFTPConnectionString=, 
        rssConfig=RSSConfig(
            tempDir=, 
            seedDir=, 
            feedTemplates={
                tosho=https://feed.animetosho.org/rss2
            }
        ), 
        torrentConfig=TorrentConfig(
            clientType=Transmission, 
            clientURL=, 
            clientUser=, 
            clientPass=
        ), 
        sabnzbdConfig=SABnzbdConfig(
            sabURL=, 
            sabApiKey=
        ), 
        ircConfig=IRCConfig(
            servers={
                irc.rizon.net=[
                    #subsplease, 
                    #Styx-XDCC
                ]
            }, 
            whitelistedXDCCBots=[
                StyxXDCC, 
                CR-ARUTHA|NEW
            ]
        )
    )
)
*/
```

</details>
