### ISSUE TITLE
How to serialize a dynamic map?

### ISSUE THREAD

**Issue by chachako** [Peanuuutz/tomlkt#8]
First of all, thank you for providing such an amazing `toml` extension for **kotlinx serialization**, it's great! But I'm having a problem with it:

Suppose I need to generate the following `toml`, and the table contents are dynamically agnostic:

```toml
[dependencies]
chrono = "0.4"
futures = "0.3"
cairo-rs = { version = "^0", features = ["png"] }
```

Dynamic might mean I can't mark `TomlInlineTable` in advance, so what should I do?

```kotlin
@Serializable
internal data class Cargo(
  // @TomlInline Is it allowed here??
  val dependencies: Map<String, @Serializable(with = StringOrInlineTableSerializer::class) Any>,
)
```
